### PR TITLE
Update readme and docker-compose.yml

### PR DESCRIPTION
**Pull request by ian-sawyer**
- update docker-compose.yml to point toward default port of kotlin middleware api app
- update readme

### CODE REVIEW

**Review by ZacharyRizer — COMMENTED** [review]
What is the reason for these changes? They seem fine to me, just trying to understand why they are necessary.

**Comment by ian-sawyer** [comment]
> What is the reason for these changes? They seem fine to me, just trying to understand why they are necessary.

This is to set the default port to the one autoconfigured with Apache Tomcat for the Kotlin SpringBoot API Middleware App. This will ensure `docker-compose(.exe) up` properly sets the appropriate port for it to run on.

**Review by ZacharyRizer — APPROVED** [review]
LGTM, and thanks for the explanation.

**Review by tbolt — APPROVED** [review]
Looks good

**Pull request merged**
